backend:
  # We'll use Netlify Identity + Git Gateway after deploy.
  name: git-gateway
  branch: main

media_folder: "images"      # where files are stored in the repo
public_folder: "/images"    # how files are referenced by the site

# Optional: draft/review/publish flow; remove if you want instant publish.
publish_mode: editorial_workflow

# Optional: slug style for new entries (we don't create new pages here, so it's moot)
slug:
  encoding: "unicode"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  # Home page JSON (content/home.json)
  - name: "home"
    label: "Home Page"
    delete: false
    files:
      - label: "Home Content"
        name: "home"
        file: "content/home.json"
        fields:
          - label: "SEO"
            name: "seo"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
          - label: "Hero"
            name: "hero"
            widget: "object"
            fields:
              - { label: "Heading", name: "heading", widget: "string" }
              - { label: "Subheading", name: "subheading", widget: "text" }
              - { label: "CTA Text", name: "ctaText", widget: "string" }
              - { label: "CTA Link", name: "ctaLink", widget: "string" }
          - label: "Features"
            name: "features"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Text", name: "text", widget: "text" }
          - label: "Testimonials"
            name: "testimonials"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Quote", name: "quote", widget: "text" }

  # Services page JSON (content/services.json)
  - name: "services"
    label: "Services Page"
    delete: false
    files:
      - label: "Services Content"
        name: "services"
        file: "content/services.json"
        fields:
          - label: "SEO"
            name: "seo"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
          - { label: "Intro", name: "intro", widget: "text" }
          - label: "Services"
            name: "services"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Summary", name: "summary", widget: "text" }
              - { label: "Price Range", name: "priceRange", widget: "string" }
              - { label: "Badge", name: "badge", widget: "string", required: false }
              - label: "Bullets"
                name: "bullets"
                widget: "list"
                field: { label: "Bullet", name: "bullet", widget: "string" }
          - label: "CTA"
            name: "cta"
            widget: "object"
            fields:
              - { label: "Text", name: "text", widget: "string" }
              - { label: "Link", name: "link", widget: "string" }

  # Contact page JSON (content/contact.json)
  - name: "contact"
    label: "Contact Page"
    delete: false
    files:
      - label: "Contact Content"
        name: "contact"
        file: "content/contact.json"
        fields:
          - label: "SEO"
            name: "seo"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
          - { label: "Intro", name: "intro", widget: "text" }
          - { label: "Address", name: "address", widget: "string" }
          - { label: "Phone", name: "phone", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - label: "Business Hours"
            name: "businessHours"
            widget: "list"
            field: { label: "Line", name: "line", widget: "string" }
